---
- name: Install open ssh server
  ansible.builtin.package:
    name:
      - openssh-server
    state: present
# sshd
- name: sshd is configured
  notify:
    - restart ssh
    - enable ssh
  template:
    src: "ubuntu_sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
    backup: true
