---
- name: open ssh server install
  apt:
    name: openssh-server
    update_cache: yes
    cache_valid_time: 3600

# sshd
- name: sshd is configured
  notify:
    - restart ssh
    - enable ssh
  template:
    src: "ubuntu_sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
    backup: true
