# Debian・Ubuntu向け設定
- block:
  - name: open ssh server install
    apt:
      name: openssh-server
      update_cache: yes
      cache_valid_time: 3600

  # sshd
  - name: sshd is configured
    notify:
      - restart ssh
      - enable ssh
    template:
      src: "ubuntu_sshd_config"
      dest: "/etc/ssh/sshd_config"
      owner: root
      group: root
      mode: 0644
  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"
  tags: secure

# CentOS向け設定
- block:
  # sshd
  - name: sshd is configured
    notify:
      - restart sshd
      - enable sshd
    template:
      src: "sshd_config.j2"
      dest: "/etc/ssh/sshd_config"
      owner: root
      group: root
      mode: 0600
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"
  tags: secure
