- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: enable sshd
  service:
    name: sshd
    enabled: yes

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: enable ssh
  service:
    name: ssh
    enabled: yes

